config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#index'
  resources :drafts do
    resources :critiques
  end
  resources :critiques, only: [:edit, :update, :destroy]
  resources :genres, only: [:index, :show]
  resources :groups do
    resources :memberships, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]

  patch '/memberships/:id/confirm' => 'memberships#confirm'

  get '/index' => 'homes#index'
  get '/about' => 'homes#about'
  get '/developer' => 'homes#developer'
  get '/faqs' => 'homes#faqs'

end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :moderator, class_name: "User", foreign_key: 'user_id'

  has_many :memberships
  has_many :members, through: :memberships, class_name: "User"
  has_many :drafts
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_moderator, only: [:edit, :update, :destroy]

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @memberships = Membership.where(group: @group)
    @membership = Membership.where(user: current_user).first
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    if @group.save
      flash[:notice] = 'Success!'
      redirect_to groups_path
    else
      flash[:notice] = 'Error'
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    if @group.update(group_params)
      flash[:notice] = 'Success!'
      redirect_to group_path(@group)
    else
      render :edit
    end
  end

  def destroy
    if @group.destroy
      flash[:notice] = 'Deleted'
      redirect_to groups_path
    else
      flash[:notice] = 'Error'
      render :show
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :description)
  end

  def authorize_moderator
    @group = Group.find(params[:id])
    if current_user.id != @group.user_id
      flash[:notice] = 'You are not authorized to do that.'
      redirect_to group_path(@group)
    end
  end
end

app/views/groups/edit.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Edit This Group</h1>
    <% if @group.errors.any? %>
      <ul>
        <%= @group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <%= form_for @group do |f| %>
      <div>
        <%= f.label :name %>
      </div>
      <div>
        <%= f.text_field :name %>
      </div>
      <div>
        <%= f.label :description %>
      </div>
      <div>
        <%= f.text_area :description %>
      </div>
      <div>
        <%= f.submit %>
      </div>
    <% end %>
    <%= link_to 'Back to Group', group_path(@group) %>
    <%= yield %>
  </div>
</div>

app/views/groups/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>All Groups</h1>
    <ul>
      <% @groups.each do |group| %>
        <h3><%= link_to group.name, group_path(group) %></h3>
        <%= group.description %><br/>
        <br/>
      <% end %>
    </ul>
    <%= link_to 'Create a Group', new_group_path %><br/>
    <br/>
    <%= link_to 'See All Public Drafts', drafts_path %>
    <%= yield %>
  </div>
</div>

app/views/groups/new.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Add A Group</h1>
    <% if @group.errors.any? %>
      <ul>
        <%= @group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <%= form_for @group do |f| %>
      <div>
        <%= f.label :name %>
      </div>
      <div>
        <%= f.text_field :name %>
      </div>
      <div>
        <%= f.label :description %>
      </div>
      <div>
        <%= f.text_area :description %>
      </div>
      <div>
        <%= f.submit %>
      </div>
    <% end %>
    <%= link_to 'Back to Groups', groups_path %>
    <%= yield %>
  </div>
</div>

app/views/groups/show.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1><%= @group.name %></h1>
    <p><%= @group.description %></p>
    <% if !current_user.is_member?(@group) && current_user.id != @group.user_id %>
      <%= button_to 'Join This Group', group_memberships_path(@group), method: :post %>
    <% end %>

    <% if current_user.is_member?(@group) && current_user.id != @group.user_id %>
      <h3>Moderator:</h3>
      <p><%= @group.moderator.username %></p>
      <h3>Group Members:</h3>
      <ul>
        <% @memberships.each do |membership| %>
          <%= membership.user.username %>
        <% end %>
      </ul>
      <%= button_to 'Leave This Group', group_membership_path(@group, @membership), method: :delete %>
    <% end %>

    <% if current_user.id == @group.user_id || current_user.role == 'admin' %>
      <h3>Group Members:</h3>
      <ul>
        <% @memberships.each do |membership| %>
          <%= membership.user.username %>
          <%= button_to 'Delete Member', group_membership_path(membership.group, membership), method: :delete, data: {:confirm => "Are you sure?"} %>
        <% end %>
        <%= link_to 'Edit This Group', edit_group_path(@group) %>
        <%= button_to 'Delete This Group', group_path(@group), method: :delete, data: {:confirm => "Are you sure?"} %>
    <% end %>
    <br/>
    <%= link_to 'All Groups', groups_path %>
    <%= yield %>
  </div>
</div>