config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#index'
  resources :drafts do
    resources :critiques
  end
  resources :critiques, only: [:edit, :update, :destroy]
  resources :genres, only: [:index, :show]
  resources :groups do
    resources :memberships, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]

  patch '/memberships/:id/confirm' => 'memberships#confirm'

  get '/index' => 'homes#index'
  get '/about' => 'homes#about'
  get '/developer' => 'homes#developer'
  get '/faqs' => 'homes#faqs'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true

  has_many :drafts
  has_many :critiques

  def is_member?(group)
    @membership = Membership.where(user: self, group: group)
    if !@membership.empty?
      true
    else
      false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @memberships = Membership.where(user: @user)
    @drafts = Draft.where(user: @user)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'Success!'
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:bio)
  end
end

app/views/users/edit.html.erb
<div class="row">
  <div class="small-12 columns">
    <%= form_for @user do |f| %>
      <div>
        <%= f.label :bio %>
      </div>
      <div>
        <%= f.text_area :bio %>
      </div>
      <div>
        <%= f.submit %>
      </div>
    <% end %>

    <%= link_to 'Back to Profile', user_path(@user) %>
    <%= yield %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="small-12 columns">
    <% if @user.id == current_user.id %>
      <h1>Welcome, <%= @user.username %>!</h1>
      <h3>Bio:</h3>
      <p><%= @user.bio %></p>
      <%= link_to 'Edit Bio', edit_user_path(@user) %>
      <br/>
      <br/>
      <h3>Your Groups:</h3>
      <ul>
        <% @memberships.each do |membership| %>
          <%= link_to membership.group.name, group_path(membership.group) %><br/>
        <% end %>
      </ul>
      <h3>Your Drafts:</h3>
      <ul>
        <% @drafts.each do |draft| %>
          <%= link_to draft.title, draft_path(draft) %><br/>
          Genre: <%= draft.genre.name %><br/>
          Restriction: <%= draft.restriction %><br/>
          Summary: <%= draft.summary %><br/>
        <% end %>
      </ul>
    <% else %>
      <h1><%= @user.username %></h1>
      <h3>Bio:</h3>
      <p><%= @user.bio %></p>
      <h3>Groups:</h3>
      <ul>
        <% @memberships.each do |membership| %>
          <%= link_to membership.group.name, group_path(membership.group) %><br/>
        <% end %>
      </ul>
      <h3>Drafts:</h3>
      <ul>
        <% @drafts.each do |draft| %>
          <%= link_to draft.title, draft_path(draft) %><br/>
          <%= draft.genre.name %><br/>
          <%= draft.restriction %><br/>
          <%= draft.summary %><br/>
        <% end %>
      </ul>
    <% end %>
    <br/>
    <br/>
    <%= link_to 'Add A New Draft', new_draft_path %><br/>
    <br/>
    <%= link_to 'All Groups', groups_path %><br/>
    <%= link_to 'All Public Drafts', drafts_path %>
    <%= yield %>
  </div>
</div>