config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#index'
  resources :drafts do
    resources :critiques
  end
  resources :critiques, only: [:edit, :update, :destroy]
  resources :genres, only: [:index, :show]
  resources :groups do
    resources :memberships, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]

  patch '/memberships/:id/confirm' => 'memberships#confirm'

  get '/index' => 'homes#index'
  get '/about' => 'homes#about'
  get '/developer' => 'homes#developer'
  get '/faqs' => 'homes#faqs'

end

app/models/draft.rb
class Draft < ActiveRecord::Base
  validates :title, presence: true
  validates :restriction, presence: true
  validates :summary, presence: true
  validates :body, presence: true

  belongs_to :user
  belongs_to :genre
  has_many :critiques, dependent: :destroy
end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_to_edit, only: [:edit, :update, :destroy]

  def index
    @drafts = Draft.order("created_at DESC")
  end

  def show
    @draft = Draft.find(params[:id])
    @critiques = Critique.where(draft: @draft)
    @critique = Critique.new
  end

  def new
    @draft = Draft.new
  end

  def create
    @draft = Draft.new(draft_params)
    @draft.user_id = current_user.id
    if @draft.save
      flash[:notice] = 'Success!'
      redirect_to drafts_path
    else
      flash[:notice] = 'Error'
      render :new
    end
  end

  def edit
    @draft = Draft.find(params[:id])
  end

  def update
    if @draft.update(draft_params)
      flash[:notice] = 'Success!'
      redirect_to draft_path(@draft)
    else
      render :edit
    end
  end

  def destroy
    if @draft.destroy
      flash[:notice] = 'Deleted'
      redirect_to drafts_path
    else
      flash[:notice] = 'Error'
      render :show
    end
  end

  private

  def draft_params
    params.require(:draft).permit(:title, :genre_id, :restriction, :summary, :body)
  end

  def authorize_to_edit
    @draft = Draft.find(params[:id])
    if current_user != @draft.user #|| current_user.role != 'admin'
      flash[:notice] = 'You are not authorized to do that.'
      redirect_to draft_path(@draft)
    end
  end
end

app/views/drafts/edit.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Add a Draft:</h1>
    <% if @draft.errors.any? %>
      <ul>
        <%= @draft.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <%= form_for @draft do |f| %>
      <div>
        <%= f.label :title %>
      </div>
      <div>
        <%= f.text_field :title %>
      </div>
      <div>
        <%= f.label :genre %>
      </div>
      <div>
        <%= f.collection_select :genre_id, Genre.all, :id, :name %>
      </div>
      <div>
        <%= f.label :restriction %>
      </div>
      <div>
        <%= f.select(:restriction, [['Public'], ['Private']]) %>
      </div>
      <div>
        <%= f.label :summary %>
      </div>
      <div>
        <%= f.text_area :summary %>
      </div>
      <div>
        <%= f.label :body %>
      </div>
      <div>
        <%= f.cktext_area :body, rows: 10 %>
      </div>
      <div>
        <%= f.submit %>
      </div>
    <% end %>
    <%= link_to 'Back to Draft', draft_path(@draft) %>
    <%= yield %>
  </div>
</div>

app/views/drafts/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>All Public Drafts</h1>
    <% @drafts.each do |draft| %>
      <h3><%= link_to draft.title.html_safe, draft_path(draft) %></h3>
      <p>Author: <%= link_to draft.user.username, user_path(draft.user) %></p>
      <p>Genre: <%= link_to draft.genre.name, genre_path(draft.genre) %></p>
      <p>Restriction: <%= draft.restriction.html_safe %></p>
      <p>Summary: <%= draft.summary.html_safe %></p>
    <% end %>

    <div>
      <%= link_to 'Drafts By Genre', genres_path %>
    </div>

    <div>
      <%= link_to 'New Draft', new_draft_path %>
    </div>

    <div>
      <%= link_to 'View Writing Groups', groups_path %>
    </div>
    <%= yield %>
  </div>
</div>

app/views/drafts/new.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1>Add a Draft:</h1>
    <% if @draft.errors.any? %>
      <ul>
        <%= @draft.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <%= form_for @draft do |f| %>
      <div>
        <%= f.label :title %>
      </div>
      <div>
        <%= f.text_field :title %>
      </div>
      <div>
        <%= f.label :genre %>
      </div>
      <div>
        <%= f.collection_select :genre_id, Genre.all, :id, :name %>
      </div>
      <div>
        <%= f.label :restriction %>
      </div>
      <div>
        <%= f.select(:restriction, [['Public'], ['Private']]) %>
      </div>
      <div>
        <%= f.label :summary %>
      </div>
      <div>
        <%= f.text_area :summary %>
      </div>
      <div>
        <%= f.label :body %>
      </div>
      <div>
        <%= f.cktext_area :body, rows: 10 %>
      </div>
      <div>
        <%= f.submit %>
      </div>
    <% end %>
    <%= yield %>
  </div>
</div>

app/views/drafts/show.html.erb
<div class="row">
  <div class="small-12 columns">
    <h1><%= @draft.title.html_safe %></h1>
    <p>Author: <%= link_to @draft.user.username, user_path(@draft.user) %></p>
    <p>Genre: <%= link_to @draft.genre.name, genre_path(@draft.genre) %></p>
    <p>Restriction: <%= @draft.restriction.html_safe %></p>
    <p>Summary: <%= @draft.summary.html_safe %></p>
    <br/>
    <br/>
    <%= @draft.body.html_safe %>

    <h3>Critiques:</h3>
    <% @critiques.each do |critique| %>
      <%= critique.comment %><br/>
      <%= link_to critique.user.username, user_path(critique.user) %><br/>
      <% if current_user == critique.user || current_user.role == 'admin' %>
        <%= link_to 'Edit Critique', edit_critique_path(critique) %>
        <%= button_to 'Delete Critique', draft_critique_path(critique.draft, critique), method: :delete, data: {:confirm => "Are you sure?"} %>
      <% end %>
    <% end %>

    <h3>Critique This Draft:</h3>
    <%= form_for([@draft, @critique]) do |f| %>
      <%= f.label :comment %>
      <%= f.text_area :comment %>
      <%= f.submit %>
    <% end %>

    <div>
      <% if current_user == @draft.user || current_user.role == 'admin' %>
        <%= link_to "Edit", edit_draft_path(@draft) %>
        <%= button_to "Delete", draft_path(@draft), method: :delete, data: {:confirm => "Are you sure?"} %>
      <% end %>
    </div>

    <%= link_to 'All Public Drafts', drafts_path %>

    <%= yield %>
  </div>
</div>