config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#index'
  resources :drafts do
    resources :critiques
  end
  resources :critiques, only: [:edit, :update, :destroy]
  resources :genres, only: [:index, :show]
  resources :groups do
    resources :memberships, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]

  patch '/memberships/:id/confirm' => 'memberships#confirm'

  get '/index' => 'homes#index'
  get '/about' => 'homes#about'
  get '/developer' => 'homes#developer'
  get '/faqs' => 'homes#faqs'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Workshopper" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar">
      <ul class="title-area">
        <li class="name">
          <% if user_signed_in? %>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to 'Sign Up', new_user_registration_path %>
            <%= link_to 'Sign In', new_user_session_path %>
          <% end %>
        </li>
      </ul>
      <section class="top-bar-section">
        <ul class="right">
          <li class="divider"></li>
          <li><%= link_to "Home", index_path %></li>
          <li class="divider"></li>
          <li><%= link_to "About This Site", about_path %></li>
          <li class="divider"></li>
          <li><%= link_to "FAQs", faqs_path %></li>
          <li class="divider"></li>
          <li><%= link_to "About the Developer", developer_path %></li>
        </ul>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    <%= javascript_include_tag "application" %>

    <script>
      $(document).ready(function() {
        //<![CDATA[
            if (typeof CKEDITOR != 'undefined') { CKEDITOR.replace('draft_body'); }
        //]]>
      });
    </script>
  </body>
</html>